# Generated by Django 5.1.6 on 2025-03-10 14:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Perfil_usuario',
            new_name='PerfilUsuario',
        ),
        migrations.AlterModelTable(
            name='perfilusuario',
            table='usuarios_perfil_usuario',
        ),
    ]
