# Generated by Django 5.1.6 on 2025-03-10 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_rename_usuario_perfilusuario_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='perfilusuario',
            table='perfil_usuario',
        ),
    ]
