# Generated by Django 5.1.7 on 2025-07-20 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='desafio',
            old_name='nome',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='desafio',
            name='descricao',
        ),
        migrations.AddField(
            model_name='desafio',
            name='bau_imagem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='desafio',
            name='imagem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='desafio',
            name='meta',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='DesafioUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progresso', models.IntegerField(default=0)),
                ('finalizado', models.BooleanField(default=False)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desafios.desafio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
