# Generated by Django 5.1.7 on 2025-07-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafios', '0002_rename_nome_desafio_titulo_remove_desafio_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desafio',
            name='data_atualizacao',
        ),
        migrations.RemoveField(
            model_name='desafio',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='desafio',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='desafio',
            name='data_inicio',
        ),
    ]
