# Generated by Django 5.1.7 on 2025-04-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_amizade'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(default='fotos_perfil/default.jpg', upload_to='fotos_perfil/'),
        ),
    ]
