# Generated by Django 5.1.7 on 2025-04-14 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_perfil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, default='fotos_perfil/default.png', null=True, upload_to='fotos_perfil/'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='pontos',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pontuação'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sequencia_dias',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='vidas',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
