# Generated by Django 5.1.7 on 2025-04-14 22:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_perfil_foto_alter_perfil_pontos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='data_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='perfil',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='perfil_publico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='seguidores',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='seguidos',
            field=models.IntegerField(default=0),
        ),
    ]
