# Generated by Django 5.1.7 on 2025-04-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_perfil_bio_perfil_data_inicio_perfil_genero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita')], default='pendente', max_length=10),
        ),
    ]
