# Generated by Django 5.1.7 on 2025-04-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_perfil_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='tema',
            field=models.CharField(default='claro', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='visibilidade',
            field=models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado')], default='publico', max_length=10),
        ),
    ]
