# Generated by Django 5.1.7 on 2025-04-27 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_perfil_tema_perfil_visibilidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='pontos',
            new_name='xp',
        ),
    ]
