# Generated by Django 5.1.7 on 2025-06-02 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_rename_pontos_perfil_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='xp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Xp'),
        ),
    ]
