# Generated by Django 5.1.7 on 2025-06-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_alter_perfil_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cristal',
            field=models.IntegerField(default=0),
        ),
    ]
