# Generated by Django 5.1.7 on 2025-06-22 15:03

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_perfil_cristal'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cooldown_ofensiva',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AddField(
            model_name='perfil',
            name='max_vidas',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ultima_ofensiva_usada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ultima_restauracao_vida',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='perfil',
            name='vidas_atuais',
            field=models.IntegerField(default=5),
        ),
    ]
