# Generated by Django 5.1.7 on 2025-06-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_perfil_cooldown_ofensiva_perfil_max_vidas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='vidas',
        ),
    ]
