# Generated by Django 5.1.7 on 2025-06-22 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_remove_perfil_vidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='intervalo_restauracao_por_vida',
            field=models.DurationField(default=datetime.timedelta(seconds=900)),
        ),
    ]
