# Generated by Django 5.1.7 on 2025-06-22 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_perfil_intervalo_restauracao_por_vida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='perfil_publico',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='status',
        ),
    ]
