# Generated by Django 5.1.7 on 2025-07-17 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
        ('usuarios', '0018_remove_perfil_perfil_publico_remove_perfil_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='divisao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ranking.divisao'),
        ),
    ]
