# Generated by Django 5.1.7 on 2026-07-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_perfil_divisao'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='tempo_estudo',
            field=models.CharField(
                blank=True,
                choices=[
                    ('leve', 'Leve — 5 minutos'),
                    ('regular', 'Regular — 10 minutos'),
                    ('foco_total', 'Foco total — 20 minutos'),
                ],
                help_text='Preferência de duração de estudo definida no onboarding.',
                max_length=20,
                null=True,
            ),
        ),
    ]
