# Generated by Django 5.1.6 on 2026-09-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0020_perfil_tempo_estudo"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="avatar",
            field=models.CharField(
                choices=[
                    ("coruja-logica", "Coruja Lógica"),
                    ("guardiao-dos-vetores", "Guardião dos Vetores"),
                    ("explorador-azul", "Explorador Azul"),
                    ("raposa-dev", "Raposa Dev"),
                    ("hacker-neon", "Hacker Neon"),
                    ("robo-aprendiz", "Robô Aprendiz"),
                    ("explorador-verde", "Explorador Verde"),
                    ("explorador-cyber", "Explorador Cyber"),
                    ("robo-advanced", "Robô Advanced"),
                    ("lenda-do-percurso", "Lenda do Percurso Lendário"),
                    ("mestre-dos-loops", "Mestre dos Loops"),
                    ("panda-code", "Panda Code"),
                ],
                default="coruja-logica",
                help_text="Avatar do catálogo selecionado pelo usuário.",
                max_length=50,
            ),
        ),
    ]
