# Generated by Django 5.1.7 on 2026-09-16 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_conquista_conquistausuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='amizade',
            constraint=models.CheckConstraint(condition=models.Q(('remetente', models.F('destinatario')), _negated=True), name='amizade_usuarios_distintos'),
        ),
    ]
