# Generated by Django 5.1.7 on 2026-09-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0023_amizade_amizade_usuarios_distintos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perfil",
            name="cooldown_ofensiva",
        ),
        migrations.RemoveField(
            model_name="perfil",
            name="ultima_ofensiva_usada",
        ),
        migrations.AddField(
            model_name="perfil",
            name="ultima_estacao_ofensiva",
            field=models.DateField(
                blank=True,
                help_text="Último dia em que uma estação completa contou para a ofensiva.",
                null=True,
            ),
        ),
    ]
