# Generated by Django 5.1.7 on 2025-07-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisao',
            name='imagem',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='divisao',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
