# Generated by Django 5.1.7 on 2025-04-27 19:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('completado', 'Completado'), ('livre', 'Livre'), ('bloqueado', 'Bloqueado')], max_length=50)),
                ('icone', models.CharField(choices=[('check', 'Check'), ('porcentagem', 'Porcentagem'), ('cadeado', 'Cadeado')], max_length=50)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('mcq', 'Múltipla Escolha'), ('code', 'Código')], max_length=50)),
                ('categoria', models.CharField(choices=[('aula', 'Aula'), ('quiz', 'Quiz')], max_length=100)),
                ('dificuldade', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('xp', models.IntegerField(default=10)),
                ('bloqueado', models.BooleanField(default=True)),
                ('concluido', models.BooleanField(default=False)),
                ('modulo', models.CharField(choices=[('while', 'While'), ('do-while', 'Do-While'), ('for', 'For')], max_length=50)),
                ('origem', models.CharField(choices=[('estatica', 'Estática'), ('ia', 'Gerada por IA')], default='estatica', max_length=10)),
                ('alternativas', models.JSONField(blank=True, null=True)),
                ('resposta_correta', models.CharField(blank=True, max_length=255, null=True)),
                ('explicacao', models.TextField(blank=True, null=True)),
                ('estacao', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='exercicios.estacao')),
            ],
            options={
                'db_table': 'exercicio',
            },
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secoes', to='exercicios.modulo')),
            ],
        ),
        migrations.AddField(
            model_name='estacao',
            name='secao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estacoes', to='exercicios.secao'),
        ),
    ]
