# Generated by Django 5.1.6 on 2025-03-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('mcq', 'Múltipla Escolha'), ('code', 'Código')], max_length=50)),
                ('dificuldade', models.IntegerField(default=1)),
            ],
        ),
    ]
