# Generated by Django 5.1.7 on 2025-04-27 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='icone',
        ),
    ]
