# Generated by Django 5.1.6 on 2025-03-10 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exercicio',
            table='exercicio',
        ),
    ]
