# Generated by Django 5.1.7 on 2025-04-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0002_remove_modulo_icone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='status',
        ),
        migrations.AddField(
            model_name='estacao',
            name='status',
            field=models.CharField(choices=[('completado', 'Completado'), ('livre', 'Livre'), ('bloqueado', 'Bloqueado')], default='livre', max_length=50),
        ),
        migrations.AddField(
            model_name='secao',
            name='status',
            field=models.CharField(choices=[('completado', 'Completado'), ('livre', 'Livre'), ('bloqueado', 'Bloqueado')], default='livre', max_length=50),
        ),
    ]
