# Generated by Django 5.1.7 on 2025-03-23 22:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0003_exercicio_bloqueado_exercicio_categoria_exercicio_xp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='modulo',
            field=models.CharField(choices=[('while', 'While'), ('do-while', 'Do-While'), ('for', 'For')], default='while', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='categoria',
            field=models.CharField(choices=[('aula', 'Aula'), ('quiz', 'Quiz')], max_length=100),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='dificuldade',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
