# Generated by Django 5.1.7 on 2025-04-27 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0003_remove_modulo_status_estacao_status_secao_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacao',
            name='descricao',
        ),
    ]
