# Generated by Django 5.1.7 on 2025-05-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0004_remove_estacao_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercicio',
            name='alternativas',
        ),
        migrations.AddField(
            model_name='exercicio',
            name='alternativa_a',
            field=models.CharField(default='sem alternativa', max_length=300),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='alternativa_b',
            field=models.CharField(default='sem alternativa', max_length=300),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='alternativa_c',
            field=models.CharField(default='sem alternativa', max_length=300),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='alternativa_d',
            field=models.CharField(default='sem alternativa', max_length=300),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='resposta_correta',
            field=models.CharField(choices=[('A', 'Alternativa A'), ('B', 'Alternativa B'), ('C', 'Alternativa C'), ('D', 'Alternativa D')], default='A', max_length=1),
            preserve_default=False,
        ),
    ]
