# Generated by Django 5.1.7 on 2025-03-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0004_exercicio_modulo_alter_exercicio_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
    ]
