# Generated by Django 5.1.7 on 2025-04-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0005_exercicio_concluido'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='alternativas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='explicacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='origem',
            field=models.CharField(choices=[('estatica', 'Estática'), ('ia', 'Gerada por IA')], default='estatica', max_length=10),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='resposta_correta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
