# Generated by Django 5.1.7 on 2025-05-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0005_remove_exercicio_alternativas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='alternativa_a',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='alternativa_b',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='alternativa_c',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='alternativa_d',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
