# Generated by Django 5.1.7 on 2025-05-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0006_alter_exercicio_alternativa_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercicio',
            name='descricao',
        ),
        migrations.AddField(
            model_name='exercicio',
            name='codigo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='enunciado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
