# Generated by Django 5.1.7 on 2025-04-27 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0006_exercicio_alternativas_exercicio_explicacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('completado', 'Completado'), ('livre', 'Livre'), ('bloqueado', 'Bloqueado')], max_length=50)),
                ('icone', models.CharField(choices=[('check', 'Check'), ('porcentagem', 'Porcentagem'), ('cadeado', 'Cadeado')], max_length=50)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='exercicio',
            name='estacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='exercicios.estacao'),
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secoes', to='exercicios.modulo')),
            ],
        ),
        migrations.AddField(
            model_name='estacao',
            name='secao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estacoes', to='exercicios.secao'),
        ),
    ]
