# Generated by Django 5.1.7 on 2025-05-04 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0007_remove_exercicio_descricao_exercicio_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercicios.modulo'),
        ),
    ]
