# Generated by Django 5.1.7 on 2025-04-27 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0007_estacao_modulo_exercicio_estacao_secao_estacao_secao_and_more'),
    ]

    