# Generated by Django 5.1.7 on 2025-05-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0008_alter_exercicio_modulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercicio',
            old_name='alternativa_a',
            new_name='alternativa_1',
        ),
        migrations.RenameField(
            model_name='exercicio',
            old_name='alternativa_b',
            new_name='alternativa_2',
        ),
        migrations.RenameField(
            model_name='exercicio',
            old_name='alternativa_c',
            new_name='alternativa_3',
        ),
        migrations.RenameField(
            model_name='exercicio',
            old_name='alternativa_d',
            new_name='alternativa_4',
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='resposta_correta',
            field=models.CharField(choices=[('1', 'Alternativa 1'), ('2', 'Alternativa 2'), ('3', 'Alternativa 3'), ('4', 'Alternativa 4')], max_length=1),
        ),
    ]
