# Generated by Django 5.1.7 on 2025-05-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0009_rename_alternativa_a_exercicio_alternativa_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercicio',
            name='bloqueado',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='concluido',
        ),
        migrations.AddField(
            model_name='exercicio',
            name='status',
            field=models.CharField(choices=[('bloqueado', 'Bloqueado'), ('livre', 'Livre'), ('concluido', 'Concluído')], default='bloqueado', max_length=20),
        ),
    ]
