# Generated by Django 5.1.7 on 2025-05-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0010_remove_exercicio_bloqueado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='status',
            field=models.CharField(choices=[('livre', 'Livre'), ('concluido', 'Concluído')], default='livre', max_length=20),
        ),
    ]
