# Generated by Django 5.1.7 on 2025-06-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0011_alter_exercicio_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercicio',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='estacao',
            name='status',
            field=models.CharField(choices=[('completado', 'Completado'), ('livre', 'Livre'), ('bloqueado', 'Bloqueado')], default='bloqueado', max_length=50),
        ),
    ]
