# Generated by Django 5.1.7 on 2025-06-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0012_remove_exercicio_categoria_alter_estacao_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estacao',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='exercicio',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='secao',
            options={'ordering': ['ordem', 'id']},
        ),
        migrations.AddField(
            model_name='secao',
            name='ordem',
            field=models.PositiveIntegerField(default=0, help_text='Define a ordem de exibição da seção dentro do módulo (menor número aparece primeiro).'),
        ),
        migrations.AlterModelTable(
            name='exercicio',
            table=None,
        ),
    ]
