# Generated by Django 5.1.7 on 2025-06-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0013_alter_estacao_options_alter_exercicio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulo',
            options={'ordering': ['ordem', 'id']},
        ),
        migrations.AddField(
            model_name='modulo',
            name='ordem',
            field=models.PositiveIntegerField(default=0, help_text='Define a ordem de exibição do módulo (menor número aparece primeiro).'),
        ),
    ]
