# Generated by Django 5.1.7 on 2025-06-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0014_alter_modulo_options_modulo_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='categoria',
            field=models.CharField(choices=[('aula', 'Aula'), ('quiz', 'Quiz')], default='aula', max_length=10),
        ),
    ]
