# Generated by Django 5.1.7 on 2025-06-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0015_exercicio_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='resposta_texto_codigo',
            field=models.TextField(blank=True, help_text='Resposta esperada para exercícios de preenchimento de lacuna ou código.', null=True),
        ),
    ]
