# Generated by Django 5.1.7 on 2025-06-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0016_exercicio_resposta_texto_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='comb_par1_col1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Par 1 - Item Coluna 1'),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='comb_par1_col2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Par 1 - Item Coluna 2 (Correspondente)'),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='comb_par2_col1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Par 2 - Item Coluna 1'),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='comb_par2_col2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Par 2 - Item Coluna 2 (Correspondente)'),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='comb_par3_col1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Par 3 - Item Coluna 1'),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='comb_par3_col2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Par 3 - Item Coluna 2 (Correspondente)'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='resposta_correta',
            field=models.CharField(blank=True, choices=[('1', 'Alternativa 1'), ('2', 'Alternativa 2'), ('3', 'Alternativa 3'), ('4', 'Alternativa 4')], help_text='Relevante apenas para exercícios de Múltipla Escolha.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='tipo',
            field=models.CharField(choices=[('mcq', 'Múltipla Escolha'), ('code', 'Código'), ('combinacao', 'Combinação')], max_length=50),
        ),
    ]
