# Generated by Django 5.1.7 on 2025-06-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0017_exercicio_comb_par1_col1_exercicio_comb_par1_col2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='resposta_vf_correta',
            field=models.BooleanField(blank=True, help_text='Resposta correta para exercícios de Verdadeiro ou Falso (True para Verdadeiro, False para Falso).', null=True),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='tipo',
            field=models.CharField(choices=[('mcq', 'Múltipla Escolha'), ('code', 'Código'), ('combinacao', 'Combinação'), ('vf', 'Verdadeiro ou Falso')], max_length=50),
        ),
    ]
