# Generated by Django 5.1.7 on 2025-06-14 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0018_exercicio_resposta_vf_correta_alter_exercicio_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercicio',
            name='origem',
        ),
    ]
