# Generated by Django 5.1.7 on 2025-06-14 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0019_remove_exercicio_origem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercicio',
            name='categoria',
        ),
    ]
