# Generated by Django 5.1.7 on 2025-06-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0020_remove_exercicio_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
