# Generated by Django 5.1.7 on 2025-06-23 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0021_alter_exercicio_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercicio',
            name='dificuldade',
        ),
    ]
