# Generated by Django 5.1.7 on 2025-06-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0022_remove_exercicio_dificuldade'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem para exercícios informativos.', null=True, upload_to='exercicios/imagens/'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='tipo',
            field=models.CharField(choices=[('mcq', 'Múltipla Escolha'), ('code', 'Código'), ('combinacao', 'Combinação'), ('info', 'Informativo'), ('vf', 'Verdadeiro ou Falso')], max_length=50),
        ),
    ]
