# Generated by Django 5.1.7 on 2025-06-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0023_exercicio_imagem_alter_exercicio_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercicio',
            name='comb_par1_col1',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='comb_par1_col2',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='comb_par2_col1',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='comb_par2_col2',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='comb_par3_col1',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='comb_par3_col2',
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='tipo',
            field=models.CharField(choices=[('mcq', 'Múltipla Escolha'), ('code', 'Código'), ('lacuna', 'Lacuna'), ('info', 'Informativo'), ('vf', 'Verdadeiro ou Falso')], max_length=50),
        ),
    ]
