# Generated by Django 5.1.7 on 2025-07-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0024_remove_exercicio_comb_par1_col1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='resposta_correta',
            field=models.CharField(blank=True, choices=[('1', 'Alternativa 1'), ('2', 'Alternativa 2'), ('3', 'Alternativa 3'), ('4', 'Alternativa 4')], help_text='Relevante para exercícios de Múltipla Escolha.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='resposta_texto_codigo',
            field=models.TextField(blank=True, help_text='Resposta esperada para exercícios de preencher a lacuna.', null=True),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='tipo',
            field=models.CharField(choices=[('mcq', 'Múltipla Escolha'), ('lacuna', 'Lacuna'), ('info', 'Informativo'), ('vf', 'Verdadeiro ou Falso')], max_length=50),
        ),
    ]
