# Generated by Django 5.1.7 on 2026-07-26

from django.db import migrations, models


def criar_estacao_demonstracao(apps, schema_editor):
    Modulo = apps.get_model('exercicios', 'Modulo')
    Secao = apps.get_model('exercicios', 'Secao')
    Estacao = apps.get_model('exercicios', 'Estacao')
    Exercicio = apps.get_model('exercicios', 'Exercicio')

    modulo, _ = Modulo.objects.get_or_create(
        nome='Demonstração',
        defaults={
            'descricao': 'Uma introdução curta à lógica de programação em C.',
            'ordem': 0,
        },
    )
    secao, _ = Secao.objects.get_or_create(
        modulo=modulo,
        nome='Experimente a Cventure',
        defaults={'status': 'livre', 'ordem': 0},
    )
    estacao, _ = Estacao.objects.get_or_create(
        secao=secao,
        nome='Primeiros passos em C',
        defaults={'status': 'livre', 'disponivel_para_visitantes': True},
    )
    if not estacao.disponivel_para_visitantes:
        estacao.disponivel_para_visitantes = True
        estacao.save(update_fields=['disponivel_para_visitantes'])

    exercicios = [
        {
            'titulo': 'O que é um algoritmo?',
            'enunciado': 'Um algoritmo é uma sequência de passos para resolver um problema. Vamos praticar esse conceito em C.',
            'tipo': 'info',
            'xp': 0,
        },
        {
            'titulo': 'Resultado de uma soma',
            'enunciado': 'Qual será o valor impresso pelo código?',
            'codigo': 'int resultado = 2 + 3;\nprintf("%d", resultado);',
            'tipo': 'mcq',
            'alternativa_1': '2',
            'alternativa_2': '3',
            'alternativa_3': '5',
            'alternativa_4': '23',
            'resposta_correta': '3',
            'xp': 0,
        },
        {
            'titulo': 'Variáveis em C',
            'enunciado': 'A instrução "int idade = 18;" cria uma variável inteira chamada idade.',
            'tipo': 'vf',
            'resposta_vf_correta': True,
            'xp': 0,
        },
    ]

    for dados in exercicios:
        titulo = dados.pop('titulo')
        Exercicio.objects.get_or_create(
            estacao=estacao,
            titulo=titulo,
            defaults={**dados, 'modulo': modulo, 'status': 'livre'},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0025_alter_exercicio_resposta_correta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacao',
            name='disponivel_para_visitantes',
            field=models.BooleanField(
                default=False,
                help_text='Libera esta estação somente na experiência de demonstração.',
            ),
        ),
        migrations.RunPython(criar_estacao_demonstracao, migrations.RunPython.noop),
    ]
