# Generated by Django 5.1.7 on 2026-08-08 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0026_estacao_demonstracao_visitante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercicio',
            name='status',
        ),
        migrations.CreateModel(
            name='ExercicioUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('livre', 'Livre'), ('concluido', 'Concluído')], default='livre', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresso_usuarios', to='exercicios.exercicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
