# Generated by Django 5.1.7 on 2026-08-16 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0028_exerciciousuario_xp_concedido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('enunciado_incorreto', 'Enunciado incorreto'), ('resposta_incorreta', 'Resposta incorreta'), ('codigo_com_problema', 'Código com problema'), ('outro', 'Outro')], max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('resolvido', 'Resolvido')], default='pendente', max_length=20)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='exercicios.exercicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de exercício',
                'verbose_name_plural': 'Reportes de exercícios',
                'ordering': ['-criado_em'],
            },
        ),
    ]
