# Generated by Django 5.1.7 on 2026-08-23 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0029_reporteexercicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacao',
            name='status',
        ),
        migrations.RemoveField(
            model_name='secao',
            name='status',
        ),
    ]
