# Generated by Django 5.1.7 on 2026-08-23 19:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0030_remove_estacao_status_remove_secao_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciciousuario',
            options={'verbose_name': 'Progresso de Exercício', 'verbose_name_plural': 'Progresso de Exercícios'},
        ),
        migrations.AlterUniqueTogether(
            name='exerciciousuario',
            unique_together={('usuario', 'exercicio')},
        ),
    ]
