# Generated by Django 5.1.7 on 2026-09-13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("exercicios", "0031_alter_exerciciousuario_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TentativaEstacao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("iniciada_em", models.DateTimeField(default=django.utils.timezone.now)),
                ("concluida_em", models.DateTimeField(blank=True, null=True)),
                ("duracao_segundos", models.PositiveIntegerField(blank=True, null=True)),
                ("primeira_conclusao", models.BooleanField(default=False)),
                ("acertos", models.PositiveIntegerField(default=0)),
                ("erros", models.PositiveIntegerField(default=0)),
                ("percentual_acertos", models.PositiveSmallIntegerField(default=0)),
                ("xp_ganho", models.PositiveIntegerField(default=0)),
                ("estacao", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tentativas", to="exercicios.estacao")),
                ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Tentativa de estação",
                "verbose_name_plural": "Tentativas de estação",
                "ordering": ["-iniciada_em"],
            },
        ),
    ]
