# Generated by Django 5.1.7 on 2026-09-17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exercicios", "0032_tentativaestacao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BauEstacaoUsuario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cristais_recebidos", models.PositiveIntegerField(default=5)),
                ("xp_recebido", models.PositiveIntegerField(default=25)),
                ("coletado_em", models.DateTimeField(auto_now_add=True)),
                ("secao", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="bau_coletas", to="exercicios.secao")),
                ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Baú de estação coletado",
                "verbose_name_plural": "Baús de estação coletados",
                "unique_together": {("usuario", "secao")},
            },
        ),
    ]
