# Generated by Django 5.1.7 on 2026-09-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercicios", "0033_bauestacaousuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercicio",
            name="respostas_aceitas",
            field=models.JSONField(blank=True, default=list, help_text="Outras respostas aceitas para a lacuna."),
        ),
    ]
