# Generated by Django 5.1.7 on 2026-09-20

from django.db import migrations, models


def definir_ilustracao_loops(apps, schema_editor):
    Modulo = apps.get_model("exercicios", "Modulo")
    Modulo.objects.filter(nome__iexact="Loops").update(imagem="img/modulos/loops.svg")


class Migration(migrations.Migration):
    dependencies = [
        ("exercicios", "0034_exercicio_respostas_aceitas"),
    ]

    operations = [
        migrations.AddField(
            model_name="modulo",
            name="imagem",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Caminho da ilustração estática do módulo. Ex.: img/modulos/loops.svg",
                max_length=255,
            ),
        ),
        migrations.RunPython(definir_ilustracao_loops, migrations.RunPython.noop),
    ]
